version: "3"
services:
  # Для запуска приложения запустите: docker-compose up web
  web:
    image: nginx:1.17-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/config/nginx.conf
      - ./:/code
    command: nginx -c /config/nginx.conf
    user: root
    ports:
      - "8080:8080"
    depends_on:
      - fpm
      - db_viz
    stop_signal: SIGTERM
    networks:
      - app-network


  # Процесс fpm
  fpm:
    build: ./docker/php
    volumes:
      - ./:/code
    networks:
      - app-network

  # База MySQL
  db_viz:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: guest
      MYSQL_DATABASE: db
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
    ports:
      - 3307:3306
    networks:
      - app-network



volumes:
  mysql_data: {}


  #Docker Networks
networks:
  app-network:
    driver: bridge